# config.toml
# https://github.com/djuelg-student

#hugo server --theme=dj_blog --buildDrafts  --bind="0.0.0.0"

baseurl = "http://0.0.0.0/"
title = "Shapez Theme"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "dj_blog"
paginate = 6
PaginatePath = "page"
googleAnalytics = "UA-123-45"

[author]
    name = "djuelg-student"

[params]
    title_l1 = "Shapez Theme"
    title_l2 = ""
    subtitle_l1 = "Shapez is a theme created for hugo"
    subtitle_l2 = "with SVG pictures as partials."
    subtitle_l3 = ""

    # Enter links for the buttons (button one has the house sign)
    button_1 = "/"
    button_2 = "/playground/"
    button_3 = "/about/"

    # Footer; Markdown accepted here.
    footer = "Copyright 2016"

    keywords = "hugo, blog, Shapez, SVG, designer"

    logo = "/images/logo.png"