# config.toml
# https://github.com/djuelg-student

baseurl = "http://0.0.0.0/"
title = "Shapez Theme"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "dj_blog"
paginate = 10
PaginatePath = "/"
googleAnalytics = "UA-123-45"

[author]
    name = "Sample Author"

[params]
    header_l1 = "Headline,"
    header_l2 = "wich can be very long"

    description_l1 = "Im am subtitle wich is not too long, but I'm"
    description_l2 = "also a two-liner..."

    # Enter links for the buttons (button one has the house sign)
    button_1 = ""
    button_2 = ""
    button_3 = ""

    # Footer; Markdown accepted here.
    footer = "Copyright 2016"

    keywords = "hugo, blog, Shapez, SVG, designer"