# config.toml
# https://github.com/djuelg-student

#hugo server --theme=dj_blog --buildDrafts  --bind="0.0.0.0"

baseurl = "http://0.0.0.0/"
title = "Shapez Theme"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "dj_blog"
paginate = 1
PaginatePath = "page"
googleAnalytics = "UA-123-45"

[author]
    name = "Sample Author"

[params]
    title_l1 = "Headline,"
    title_l2 = "wich can be very l0ng"
    subtitle_l1 = "Im am subtitle wich is not too long,"
    subtitle_l2 = "but I'm also a two-liner..."
    subtitle_l3 = "Now with a third line!"

    # Enter links for the buttons (button one has the house sign)
    button_1 = "/#scroll-down"
    button_2 = "/playground/"
    button_3 = "/about/"

    # Footer; Markdown accepted here.
    footer = "Copyright 2016"

    keywords = "hugo, blog, Shapez, SVG, designer"

    logo = "/images/logo.png"