# Creator: djuelg @ https://github.com/djuelg
# Run via: hugo server --theme=Shapez-Theme --buildDrafts --bind="0.0.0.0"

baseurl = "http://0.0.0.0/"
title = "Shapez Theme"
theme = "Shapez-Theme"
copyright = "Copyright (c) 2016, djuelg; all rights reserved."
[author]
    name = "djuelg"
    
languageCode = "en-US"
MetaDataFormat = "toml"
paginate = 8
PaginatePath = "page"
googleAnalytics = ""

[params]
    # Homepage Start-Screen, variables can be left empty
    title_l1 = "Shapez Theme"
    title_l2 = ""
    subtitle_l1 = "Shapez is a theme created for hugo"
    subtitle_l2 = "with SVG pictures, CSS3 magic,"
    subtitle_l3 = "struggle and love."
    title_link = "/about/"
    subtitle_link = ""

    message = "I'm a optional important message!"

    # Enter links for the buttons (button one has the house sign), shouldn't be left empty
    button_1 = "/"
    button_2 = "/playground/"
    button_3 = "/about/"

    keywords = "hugo, blog, Shapez, SVG, design"

    logo = "images/logo.png"