# config.toml
# https://github.com/djuelg-student

baseurl = "http://0.0.0.0/"
title = "Scorpiorse"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "dj_blog"
paginate = 10
PaginatePath = "/"

[author]
    name = "Sample Author"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]
    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Example site for Slender, a minimalist theme for Hugo."
    keywords = "hugo, blog, Scorpiorse, SVG, designer"

    # Footer; Markdown accepted here.
    footer = "Copyright 2016  ·  Sample Author"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = ""

[menu]
    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = ""
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/"
    weight     = 1