#hugo server --theme=dj_blog --buildDrafts  --bind="0.0.0.0"
#https://github.com/spf13/hugo/tree/master/docs/content/content


baseurl = "http://0.0.0.0/"
name = "dj_blog"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
homepage = "http://siteforthistheme.com/"
tags = ["hugo", "blog", "Scorpiorse", "SVG", "designer"]
min_version = 0.14

[author]
  name = "Dominik Juelg"
  homepage = "https://github.com/djuelg-student"